<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.consilens</groupId>
        <artifactId>consilens-connector-plugins</artifactId>
        <version>0.1-SNAPSHOT</version>
    </parent>

    <artifactId>consilens-connector-all</artifactId>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.consilens</groupId>
            <artifactId>consilens-connector-mysql</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>com.consilens</groupId>
            <artifactId>consilens-connector-postgresql</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>com.consilens</groupId>
            <artifactId>consilens-connector-oracle</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>com.consilens</groupId>
            <artifactId>consilens-connector-sqlserver</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>com.consilens</groupId>
            <artifactId>consilens-connector-presto</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>com.consilens</groupId>
            <artifactId>consilens-connector-clickhouse</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>com.consilens</groupId>
            <artifactId>consilens-connector-trino</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>com.consilens</groupId>
            <artifactId>consilens-connector-tidb</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>com.consilens</groupId>
            <artifactId>consilens-connector-starrocks</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>com.consilens</groupId>
            <artifactId>consilens-connector-doris</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>com.consilens</groupId>
            <artifactId>consilens-connector-oceanbase</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>

</project>
