package com.consilens.agent.api.event;

/**
 * Ordered, append-only event vocabulary (section 21.2 of the design).
 */
public enum AgentEventType {
    USER_MESSAGE,
    STEERING_QUEUED,
    RUN_STARTED,
    TURN_STARTED,
    ASSISTANT_MESSAGE,
    ASSISTANT_DELTA,
    MODEL_USAGE,
    TOOL_PROPOSED,
    TOOL_BLOCKED,
    TOOL_STARTED,
    TOOL_PROGRESS,
    TOOL_COMPLETED,
    TOOL_BATCH_REJECTED,
    QUESTION_REQUIRED,
    SECRET_INPUT_REQUIRED,
    SECRET_PROVIDED,
    APPROVAL_REQUIRED,
    APPROVAL_DECIDED,
    WORKING_STATE_PATCHED,
    PLAN_PREPARED,
    PLAN_COMMIT_STARTED,
    PLAN_ACTION_STARTED,
    PLAN_ACTION_COMPLETED,
    PLAN_ACTION_FAILED,
    PLAN_COMMIT_COMPLETED,
    RESOURCE_CREATED,
    RUN_SUSPENDED,
    TURN_COMPLETED,
    RUN_COMPLETED,
    RUN_FAILED,
    RUN_CANCELLED
}
