CREATE TABLE IF NOT EXISTS cs_server_node (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    node_key VARCHAR(128) NOT NULL UNIQUE,
    host VARCHAR(64) NOT NULL,
    port INT NOT NULL,
    machine_code VARCHAR(128),
    status VARCHAR(32) NOT NULL,
    load_average DOUBLE,
    available_memory_mb DOUBLE,
    heartbeat_time TIMESTAMP NOT NULL,
    status_update_time TIMESTAMP,
    status_update_by VARCHAR(128),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS cs_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_key VARCHAR(64) NOT NULL UNIQUE,
    serial_no VARCHAR(128) NOT NULL UNIQUE,
    tenant_id VARCHAR(64),
    trace_id VARCHAR(128) NOT NULL,
    correlation_id VARCHAR(64),
    request_payload CLOB NOT NULL,
    request_hash VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    priority INT NOT NULL DEFAULT 5,
    schedule_time TIMESTAMP NOT NULL,
    submit_time TIMESTAMP NOT NULL,
    start_time TIMESTAMP,
    end_time TIMESTAMP,
    execute_node_key VARCHAR(128),
    result_artifact_id VARCHAR(64),
    error_code VARCHAR(64),
    error_message CLOB,
    retry_count INT NOT NULL DEFAULT 0,
    max_retry_count INT NOT NULL DEFAULT 3,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS cs_task_command (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    command_key VARCHAR(64) NOT NULL UNIQUE,
    task_id BIGINT NOT NULL,
    shard_key VARCHAR(64) NOT NULL,
    shard_slot INT NOT NULL,
    status VARCHAR(32) NOT NULL,
    execute_node_key VARCHAR(128),
    lock_time TIMESTAMP,
    lock_until TIMESTAMP,
    schedule_time TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_cs_task_command_task_id FOREIGN KEY (task_id) REFERENCES cs_task (id)
);

CREATE TABLE IF NOT EXISTS cs_artifact (
    id VARCHAR(64) PRIMARY KEY,
    task_id BIGINT,
    trace_id VARCHAR(128) NOT NULL,
    artifact_type VARCHAR(32) NOT NULL,
    artifact_format VARCHAR(16) NOT NULL,
    storage_type VARCHAR(16) NOT NULL,
    storage_uri VARCHAR(512) NOT NULL,
    sha256 VARCHAR(64),
    metadata_json CLOB,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_cs_artifact_task_id FOREIGN KEY (task_id) REFERENCES cs_task (id)
);

CREATE INDEX IF NOT EXISTS idx_cs_task_status_schedule ON cs_task (status, schedule_time);
CREATE INDEX IF NOT EXISTS idx_cs_task_execute_node_status ON cs_task (execute_node_key, status);
CREATE INDEX IF NOT EXISTS idx_cs_task_trace_id ON cs_task (trace_id);
CREATE INDEX IF NOT EXISTS idx_cs_task_command_shard_status_schedule ON cs_task_command (shard_slot, status, schedule_time);
CREATE INDEX IF NOT EXISTS idx_cs_task_command_execute_node_status ON cs_task_command (execute_node_key, status);
CREATE INDEX IF NOT EXISTS idx_cs_task_command_task_id ON cs_task_command (task_id);
CREATE INDEX IF NOT EXISTS idx_cs_artifact_task_id ON cs_artifact (task_id);
CREATE INDEX IF NOT EXISTS idx_cs_artifact_trace_id ON cs_artifact (trace_id);
CREATE INDEX IF NOT EXISTS idx_cs_artifact_type_created_at ON cs_artifact (artifact_type, created_at);
