CREATE TABLE IF NOT EXISTS cs_server_node (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    node_key VARCHAR(128) NOT NULL UNIQUE,
    host VARCHAR(64) NOT NULL,
    port INT NOT NULL,
    machine_code VARCHAR(128),
    status VARCHAR(32) NOT NULL,
    load_average DOUBLE,
    available_memory_mb DOUBLE,
    heartbeat_time TIMESTAMP NOT NULL,
    status_update_time TIMESTAMP,
    status_update_by VARCHAR(128),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS cs_task_instance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instance_key VARCHAR(64) NOT NULL UNIQUE,
    definition_id BIGINT,
    serial_no VARCHAR(128) NOT NULL UNIQUE,
    tenant_id VARCHAR(64),
    trace_id VARCHAR(128) NOT NULL,
    correlation_id VARCHAR(64),
    request_payload CLOB NOT NULL,
    request_hash VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    priority INT NOT NULL DEFAULT 5,
    schedule_time TIMESTAMP NOT NULL,
    submit_time TIMESTAMP NOT NULL,
    start_time TIMESTAMP,
    end_time TIMESTAMP,
    execute_node_key VARCHAR(128),
    result_artifact_id VARCHAR(64),
    error_code VARCHAR(64),
    error_message CLOB,
    retry_count INT NOT NULL DEFAULT 0,
    max_retry_count INT NOT NULL DEFAULT 3,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS cs_task_command (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    command_key VARCHAR(64) NOT NULL UNIQUE,
    task_id BIGINT NOT NULL,
    shard_key VARCHAR(64) NOT NULL,
    shard_slot INT NOT NULL,
    status VARCHAR(32) NOT NULL,
    execute_node_key VARCHAR(128),
    lock_time TIMESTAMP,
    lock_until TIMESTAMP,
    schedule_time TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_cs_task_command_task_id FOREIGN KEY (task_id) REFERENCES cs_task_instance (id)
);

CREATE TABLE IF NOT EXISTS cs_artifact (
    id VARCHAR(64) PRIMARY KEY,
    task_id BIGINT,
    trace_id VARCHAR(128) NOT NULL,
    artifact_type VARCHAR(32) NOT NULL,
    artifact_format VARCHAR(16) NOT NULL,
    storage_type VARCHAR(16) NOT NULL,
    storage_uri VARCHAR(512) NOT NULL,
    sha256 VARCHAR(64),
    metadata_json CLOB,
    statistics_json CLOB,
    difference_count BIGINT,
    difference_truncated BOOLEAN,
    difference_rows INT,
    differences_uri VARCHAR(512),
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_cs_artifact_task_id FOREIGN KEY (task_id) REFERENCES cs_task_instance (id)
);

CREATE INDEX IF NOT EXISTS idx_cs_task_instance_status_schedule ON cs_task_instance (status, schedule_time);
CREATE INDEX IF NOT EXISTS idx_cs_task_instance_submit_time ON cs_task_instance (submit_time);
CREATE INDEX IF NOT EXISTS idx_cs_task_instance_execute_node_status ON cs_task_instance (execute_node_key, status);
CREATE INDEX IF NOT EXISTS idx_cs_task_instance_trace_id ON cs_task_instance (trace_id);
CREATE INDEX IF NOT EXISTS idx_cs_task_command_shard_status_schedule ON cs_task_command (shard_slot, status, schedule_time);
CREATE INDEX IF NOT EXISTS idx_cs_task_command_execute_node_status ON cs_task_command (execute_node_key, status);
CREATE INDEX IF NOT EXISTS idx_cs_task_command_task_id ON cs_task_command (task_id);
CREATE INDEX IF NOT EXISTS idx_cs_artifact_task_id ON cs_artifact (task_id);
CREATE INDEX IF NOT EXISTS idx_cs_artifact_trace_id ON cs_artifact (trace_id);
CREATE INDEX IF NOT EXISTS idx_cs_artifact_type_created_at ON cs_artifact (artifact_type, created_at);

CREATE TABLE IF NOT EXISTS cs_datasource (
    id BIGINT PRIMARY KEY,
    name VARCHAR(128) NOT NULL UNIQUE,
    type VARCHAR(64) NOT NULL,
    param CLOB NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS cs_task_definition (
    id BIGINT PRIMARY KEY,
    definition_key VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(128) NOT NULL UNIQUE,
    description VARCHAR(512),
    task_type VARCHAR(32) NOT NULL DEFAULT 'RUN',
    config CLOB NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    schedule_type VARCHAR(16),
    cron_expr VARCHAR(64),
    last_run_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_cs_task_instance_definition ON cs_task_instance (definition_id, submit_time);

-- ==========================================================================
-- AI Agent durable session/event/plan/secret tables (design section 26.1)
-- ==========================================================================

CREATE TABLE IF NOT EXISTS cs_ai_session (
    id VARCHAR(64) PRIMARY KEY,
    actor_id VARCHAR(128) NOT NULL,
    request_id VARCHAR(64),
    title VARCHAR(128),
    objective VARCHAR(1024),
    status VARCHAR(32) NOT NULL,
    workflow_stage VARCHAR(32) NOT NULL,
    active_run_id VARCHAR(64),
    next_seq BIGINT NOT NULL DEFAULT 0,
    snapshot_seq BIGINT NOT NULL DEFAULT 0,
    version BIGINT NOT NULL DEFAULT 0,
    lease_owner VARCHAR(128),
    lease_expires_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_cs_ai_session_actor_updated ON cs_ai_session (actor_id, updated_at);
CREATE INDEX IF NOT EXISTS idx_cs_ai_session_status_lease ON cs_ai_session (status, lease_expires_at);

CREATE TABLE IF NOT EXISTS cs_ai_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id VARCHAR(64) NOT NULL,
    session_id VARCHAR(64) NOT NULL,
    seq BIGINT NOT NULL,
    run_id VARCHAR(64),
    turn_id VARCHAR(64),
    event_type VARCHAR(48) NOT NULL,
    visibility VARCHAR(24) NOT NULL,
    schema_version INT NOT NULL,
    payload CLOB,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_cs_ai_event_session_seq UNIQUE (session_id, seq)
);
CREATE INDEX IF NOT EXISTS idx_cs_ai_event_session_run_seq ON cs_ai_event (session_id, run_id, seq);

CREATE TABLE IF NOT EXISTS cs_ai_run (
    run_id VARCHAR(64) PRIMARY KEY,
    session_id VARCHAR(64) NOT NULL,
    request_id VARCHAR(64) NOT NULL,
    resume_from_run_id VARCHAR(64),
    status VARCHAR(32) NOT NULL,
    lease_owner VARCHAR(128),
    lease_expires_at TIMESTAMP,
    turn_count INT NOT NULL DEFAULT 0,
    tool_call_count INT NOT NULL DEFAULT 0,
    token_count BIGINT NOT NULL DEFAULT 0,
    error_code VARCHAR(64),
    started_at TIMESTAMP,
    ended_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_cs_ai_run_session_request UNIQUE (session_id, request_id)
);

CREATE TABLE IF NOT EXISTS cs_ai_tool_call (
    call_id VARCHAR(64) PRIMARY KEY,
    session_id VARCHAR(64) NOT NULL,
    run_id VARCHAR(64) NOT NULL,
    turn_id VARCHAR(64),
    source_order INT NOT NULL,
    tool_name VARCHAR(96) NOT NULL,
    status VARCHAR(24) NOT NULL,
    risk_level VARCHAR(16),
    redacted_args CLOB,
    args_digest VARCHAR(64),
    idempotency_key VARCHAR(64),
    action_digest VARCHAR(64),
    result_event_seq BIGINT,
    error_code VARCHAR(64),
    retryable BOOLEAN,
    result_summary VARCHAR(1024),
    started_at TIMESTAMP,
    ended_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_cs_ai_tool_call_session_idem ON cs_ai_tool_call (session_id, idempotency_key);

CREATE TABLE IF NOT EXISTS cs_ai_approval (
    approval_id VARCHAR(64) PRIMARY KEY,
    session_id VARCHAR(64) NOT NULL,
    proposed_run_id VARCHAR(64),
    status VARCHAR(24) NOT NULL,
    action_digest VARCHAR(64) NOT NULL,
    safe_summary VARCHAR(1024),
    safe_actions_json CLOB,
    actor_id VARCHAR(128),
    decided_at TIMESTAMP,
    expires_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS cs_ai_plan (
    plan_id VARCHAR(64) PRIMARY KEY,
    session_id VARCHAR(64) NOT NULL,
    objective_id VARCHAR(64) NOT NULL,
    status VARCHAR(24) NOT NULL,
    plan_digest VARCHAR(64) NOT NULL,
    config_template_digest VARCHAR(64),
    safe_summary VARCHAR(1024),
    plan_json CLOB,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS cs_ai_plan_action (
    plan_id VARCHAR(64) NOT NULL,
    action_id VARCHAR(64) NOT NULL,
    sequence INT NOT NULL,
    action_type VARCHAR(40) NOT NULL,
    name VARCHAR(160),
    safe_args_json CLOB,
    status VARCHAR(24) NOT NULL,
    idempotency_key VARCHAR(64),
    input_digest VARCHAR(64),
    resource_type VARCHAR(32),
    resource_id VARCHAR(64),
    result_digest VARCHAR(64),
    error_code VARCHAR(64),
    retryable BOOLEAN,
    started_at TIMESTAMP,
    ended_at TIMESTAMP,
    PRIMARY KEY (plan_id, action_id),
    CONSTRAINT uk_cs_ai_plan_action_seq UNIQUE (plan_id, sequence),
    CONSTRAINT uk_cs_ai_plan_action_idem UNIQUE (plan_id, idempotency_key)
);

CREATE TABLE IF NOT EXISTS cs_ai_secret (
    secret_request_id VARCHAR(64) PRIMARY KEY,
    actor_id VARCHAR(128) NOT NULL,
    session_id VARCHAR(64) NOT NULL,
    draft_id VARCHAR(64),
    status VARCHAR(24) NOT NULL,
    cipher_algorithm VARCHAR(32),
    key_id VARCHAR(64),
    nonce VARBINARY(64),
    ciphertext VARBINARY(2048),
    tag VARBINARY(64),
    read_count INT NOT NULL DEFAULT 0,
    max_reads INT NOT NULL DEFAULT 8,
    expires_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL,
    consumed_at TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_cs_ai_secret_session_status ON cs_ai_secret (session_id, status, expires_at);

CREATE TABLE IF NOT EXISTS cs_ai_snapshot (
    session_id VARCHAR(64) NOT NULL,
    seq BIGINT NOT NULL,
    working_state CLOB NOT NULL,
    conversation_summary CLOB,
    schema_version INT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    PRIMARY KEY (session_id, seq)
);
